# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enclave < Formula
  desc "A tool to run any command in a sandboxed environment using macOS's sandbox-exec"
  homepage "https://github.com/zhuxiangxiao/enclave"
  version "3.1.0-beta.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/zhuxiangxiao/enclave/releases/download/v3.1.0-beta.1/enclave_3.1.0-beta.1_darwin_amd64.tar.gz"
    sha256 "efe1f26c8479575ad602f16dced106ebb32260f04561e70511feb959793b65f4"

    define_method(:install) do
      bin.install "enclave"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/zhuxiangxiao/enclave/releases/download/v3.1.0-beta.1/enclave_3.1.0-beta.1_darwin_arm64.tar.gz"
    sha256 "0afa76550def250ea3d06491a903556c0067044b8cf0ebb11e369b792071db62"

    define_method(:install) do
      bin.install "enclave"
    end
  end
end
