# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enclave < Formula
  desc "A tool to run any command in a sandboxed environment using macOS's sandbox-exec"
  homepage "https://github.com/zhuxiangxiao/enclave"
  version "3.1.0-alpha"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/zhuxiangxiao/enclave/releases/download/v3.1.0-alpha/enclave_3.1.0-alpha_darwin_amd64.tar.gz"
    sha256 "368349f20bd11e4a8dc89441bcf226b1aa2f755a7e45a2670180bda13c81a81c"

    define_method(:install) do
      bin.install "enclave"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/zhuxiangxiao/enclave/releases/download/v3.1.0-alpha/enclave_3.1.0-alpha_darwin_arm64.tar.gz"
    sha256 "b0ec048f5574fc939dd41642fc257111c49635746c68af015edb63934f02218b"

    define_method(:install) do
      bin.install "enclave"
    end
  end
end
